const RX_GLOBAL_APP = {
    RX_GLOBAL_APP_LOADING_ON: 'RX_GLOBAL_APP_LOADING_ON',
    RX_GLOBAL_APP_LOADING_OFF: 'RX_GLOBAL_APP_LOADING_OFF',
}

const RX_SHIP_LIST = {
    RX_SHIP_LIST_CLEAR: 'RX_SHIP_LIST_CLEAR',
    RX_SHIP_LIST_SET: 'RX_SHIP_LIST_SET',
};

const RX_SHIP_ITEM_DETAIL = {
    RX_SHIP_ITEM_DETAIL_CLEAR: 'RX_SHIP_ITEM_DETAIL_CLEAR',
    RX_SHIP_ITEM_DETAIL_SET: 'RX_SHIP_ITEM_DETAIL_SET',
};

const RX_SHIP_PILOTS = {
    RX_SHIP_PILOTS_CLEAR: 'RX_SHIP_PILOTS_CLEAR',
    RX_SHIP_PILOTS_SET: 'RX_SHIP_PILOTS_SET',
};

export {
    RX_GLOBAL_APP,
    RX_SHIP_LIST,
    RX_SHIP_ITEM_DETAIL,
    RX_SHIP_PILOTS,
};
